### ISSUE TITLE
Can I use this Kyma Runtime

### ISSUE THREAD

**Issue by SanthoshCheekoti** [SAP/cloud-sdk-js#1378]
Hello,

Can we use this SDK on Kyma Runtime?

**Comment by FrankEssenberger** [comment]
Good morning @SanthoshCheekoti,

thanks for your question. We are currently working on this and we started already the investigation on the topic. We plan to have everything tested and documented by the end of Q3. The SDK will support the k8s based runtimes Kyma and Gardener in the near future. So currently it depends what you want to do and in which timeline. 

We see that a lot is working but there are some blind spots:
- The SDK works for cloud destinations as long as the client credentials (VCAP_SERVICES in cloud foundry) are mounted as secrets in the k8s cluster @tomfrenken - clould you comment on this and perhaps give one guide.
- For OnPremise connection a connectivity proxy is needed which needs to be configured manually on k8s runtimes in contrast to cloud foundry where this is done automatically when subscribing to the connectivity service. In principle this should work, but we have not done an E2E test.
- We have not tested the E2E flow of authentication and token handling.
- The whole logic like the typed client and convenience in request creation is not affected by the runtime.

I hope this answer your question.

Best
Frank

**Comment by SanthoshCheekoti** [comment]
Thank you. It answers my question.

**Comment by tomfrenken** [comment]
Hey @SanthoshCheekoti maybe to add to Frank's answer, if you've created secrets containing the `VCAP_SERVICES`, you have to mount them in a very specific path, e.g. following this pattern:

```
volumeMounts:
          - name: <volume-name>
            mountPath: "/etc/secrets/sapcp/<service>/<service-name>" 
            readOnly: true
```

for example, the destination service would look like this:

```
volumeMounts:
          - name: my-secret-volume
            mountPath: "/etc/secrets/sapcp/destination/my-destination-service" 
            readOnly: true
```

as mentioned we will have a more in-depth guide on how to use the SDK in k8s environments in the upcoming week(s), where we will also discuss migration from CloudFoundry applications to k8s.
