### ISSUE TITLE
Unable to Access Multi-Tenant Application via External Domain in AppRouter

### ISSUE THREAD

**Issue by yarinisraeli24** [SAP/cloud-sdk-js#5570]
### Describe the Question

I am following [this documentation](https://sap.github.io/cloud-sdk/docs/js/tutorials/multi-tenant-application) to deploy a multi-tenant application using AppRouter.  

I have successfully completed the sections:  
- [The Application](https://sap.github.io/cloud-sdk/docs/js/tutorials/multi-tenant-application#the-application)  
- [The Approuter](https://sap.github.io/cloud-sdk/docs/js/tutorials/multi-tenant-application#the-approuter)

I was able to make a request to:  
```
GET https://route-prefix-eu12-canary.cfapps.eu12.hana.ondemand.com/service
```
and received a valid response as described in the documentation.  

![Image](https://github.com/user-attachments/assets/b5b0d082-2032-4af5-aba3-1e842c5e9612)

Now, I am trying to integrate an external domain:  
```
*.i558206.playground.live.pu.ugw.cloud.sap  
```  
to AppRouter.  

#### Steps Taken  
1. Created a private domain in Cloud Foundry:  
   ```
   i558206.playground.live.pu.ugw.cloud.sap  
   ```  
2. Mapped the route to the AppRouter application.  

#### Issue  
When I attempt to access the application via the external domain, I am redirected to an authentication page instead of reaching my application.  

#### Expected Behavior  
Accessing the application through the external domain should behave similarly to the existing route, without unexpected redirections.  

#### Question  
What additional configuration is required to enable access to my application via the external domain?  

YOUR_SUBDOMAIN: eu12-canary
YOUR_REGION: eu12

![Image](https://github.com/user-attachments/assets/4f775a5d-1859-4870-9fce-f19e38a7af1c)
![Image](https://github.com/user-attachments/assets/b91882d8-6ed3-49cd-83e4-593a2152c489)
![Image](https://github.com/user-attachments/assets/5b1ed105-e094-42ca-9aab-41444b58ffa9)
![Image](https://github.com/user-attachments/assets/71654adc-9755-47fc-a030-284393ae0e09)

approuter manifest.yaml:

```
applications:
  - name: approuter
    routes:
      - route: 'route-prefix-eu12-canary.cfapps.eu12.hana.ondemand.com'
    path: .
    memory: 128M
    buildpacks:
      - nodejs_buildpack
    env:
      TENANT_HOST_PATTERN: 'route-prefix-(.*).cfapps.eu12.hana.ondemand.com'
      destinations: >
        [
          {"name":"multi-tenant-app","url":"https://multi-tenant-app.cfapps.eu12.hana.ondemand.com","forwardAuthToken":true}
        ]
    services:
      - xsuaa
      - destination
```

multi-tenant-app manifest.yaml:
```
applications:
  - name: multi-tenant-app
    path: .
    memory: 256M
    buildpacks:
      - nodejs_buildpack
    services:
      - destination
      - xsuaa
    routes:
      - route: 'multi-tenant-app.cfapps.eu12.hana.ondemand.com'
```
